const enter=document.getElementById('enter');const audio=document.getElementById('audio');const playBtn=document.getElementById('playBtn');const typewriter=document.getElementById('typewriter');const views=document.getElementById('views');const volumeFloat=document.getElementById('volumeFloat');const volumeSlider=document.getElementById('volumeSlider');const musicVolume=document.getElementById('musicVolume');const progress=document.getElementById('progress');const timeLabel=document.getElementById('timeLabel');const volumeIcon=document.getElementById('volumeIcon');
const messages=['ils enquêtent sur moi comme la CIA','mais ils ne trouvent rien.'];let messageIndex=0,pos=0,deleting=false;
function typeLoop(){const t=messages[messageIndex];if(!deleting){pos++;typewriter.textContent=t.slice(0,pos);if(pos>=t.length){deleting=true;setTimeout(typeLoop,2000);return}setTimeout(typeLoop,55)}else{pos--;typewriter.textContent=t.slice(0,pos);if(pos<=0){deleting=false;messageIndex=(messageIndex+1)%messages.length;setTimeout(typeLoop,400);return}setTimeout(typeLoop,30)}}typeLoop();
const stored=Number(localStorage.getItem('sonic_views')||0)+1;localStorage.setItem('sonic_views',stored);views.textContent=stored.toLocaleString('fr-FR');
audio.volume=.65;function syncVolume(v){audio.volume=Number(v);volumeSlider.value=v;musicVolume.value=v;volumeIcon.textContent=Number(v)===0?'🔇':Number(v)<.5?'🔉':'🔊'}volumeSlider.addEventListener('input',e=>syncVolume(e.target.value));musicVolume.addEventListener('input',e=>syncVolume(e.target.value));
enter.addEventListener('click',async()=>{enter.classList.add('hidden');volumeFloat.classList.add('visible');try{await audio.play();playBtn.textContent='❚❚'}catch(_){}});playBtn.addEventListener('click',async e=>{e.stopPropagation();if(audio.paused){try{await audio.play()}catch(_){}playBtn.textContent='❚❚'}else{audio.pause();playBtn.textContent='▶'}});audio.addEventListener('ended',()=>playBtn.textContent='▶');
function fmt(s){if(!Number.isFinite(s))return'0:00';const m=Math.floor(s/60),r=Math.floor(s%60).toString().padStart(2,'0');return `${m}:${r}`};audio.addEventListener('timeupdate',()=>{if(audio.duration){progress.value=(audio.currentTime/audio.duration)*100;timeLabel.textContent=`${fmt(audio.currentTime)} / ${fmt(audio.duration)}`}});audio.addEventListener('loadedmetadata',()=>timeLabel.textContent=`0:00 / ${fmt(audio.duration)}`);progress.addEventListener('input',()=>{if(audio.duration)audio.currentTime=(progress.value/100)*audio.duration});
const profileCard=document.getElementById('profileCard');if(profileCard&&window.matchMedia('(pointer: fine)').matches){profileCard.addEventListener('mousemove',e=>{const r=profileCard.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;profileCard.style.transform=`rotateX(${-y*6}deg) rotateY(${x*8}deg) scale3d(1.008,1.008,1.008)`});profileCard.addEventListener('mouseleave',()=>{profileCard.style.transition='transform .45s cubic-bezier(.2,.8,.2,1), box-shadow .25s ease';profileCard.style.transform='rotateX(0deg) rotateY(0deg) scale3d(1,1,1)';setTimeout(()=>profileCard.style.transition='transform .12s ease-out, box-shadow .25s ease',460)})}
// Animation du titre de l'onglet : @ Sonic_OFF s'écrit puis s'efface en boucle.
const tabText='@ Sonic_OFF';let tabPos=0,tabDeleting=false;function animateTitle(){document.title=tabText.slice(0,tabPos);if(!tabDeleting){if(tabPos<tabText.length){tabPos++;setTimeout(animateTitle,150)}else{tabDeleting=true;setTimeout(animateTitle,1400)}}else{if(tabPos>0){tabPos--;setTimeout(animateTitle,90)}else{tabDeleting=false;setTimeout(animateTitle,450)}}}animateTitle();
